### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [michaelg29/yt-tutorials#2]
Hello, thank you for your wonderful tutorials on OpenGL. I am wonderful under what license is the source code released under ? I would like to closely study it to learn from it. Thank you.

**Comment by michaelg29** [comment]
@suprafun You can use it as you please, no credit is necessary, but one would be appreciated.

**Comment by suprafun** [comment]
Thank you so very much. Would it be alright if I consider this project under MIT license ? I just want to be sure if its alright with you. Thank you again.

**Comment by michaelg29** [comment]
@suprafun Yeah that's perfect, thanks for checking.
